version: '3'
services:
  app:
    container_name: eatfy
    build: .
    ports: 
      - 3000:3000 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - db     
    networks:
      - db-network
    environment: 
      - POSTGRES_URI=postgres://postgres@db/postgres?sslmode=disable
      - API_KEY=abcd 
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - db-network
    restart: unless-stopped

volumes:
  api:
  database_postgres:                  
networks:
  db-network:
    driver: bridge